import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import styles from '../../styles/quiz/quizpage.module.css';
import { cards } from '../../Data/Routes/ReadingAssignments'
import Link from 'next/link';
import { IoPlayCircleSharp } from "react-icons/io5";
import { useSelector } from 'react-redux'; // To access authentication status from Redux
import { FaLock } from 'react-icons/fa';
import { useRouter } from 'next/router';
import { Getperformance } from '@/helperfunction/Getperformance';

export default function ReadingAssignments() {
  const { user } = useSelector((state) => state.auth); // Access authentication status
  const [userData, setUserData] = useState(null);
  const [reading, setReading] = useState(null);
  const [isClient, setIsClient] = useState(false);

  const router = useRouter();
  const { id } = router.query; // Get the dynamic `id` from the route

  const somedata = cards.find((data) => data.link === id);

  // Function to fetch user performance
  const fetchUserData = async () => {
    try {
      const data = await Getperformance(user.userId);
      setUserData(data);
    } catch (err) {
      console.error(err);
    }
  };

  // Fetch user data on initial load and when the route changes
  useEffect(() => {
    if (user?.userId) {
      fetchUserData();
    }
  }, [user?.userId]);

  // Listen for route changes and re-fetch data
  useEffect(() => {
    const handleRouteChange = () => {
      fetchUserData();
    };

    router.events.on('routeChangeComplete', handleRouteChange);

    // Cleanup the event listener on unmount
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, [router.events]);

  useEffect(() => {
    setIsClient(true); // Set to true when client-side is ready

    if (somedata) {
      // Dynamically import the lesson data
      import(`../../Data/ReadingAssignments/${somedata.data}`)
        .then((module) => setReading(module.data))
        .catch((error) => console.error('Error loading lesson data:', error));
    }
  }, [somedata]);

  if (!isClient || !somedata) {
    return <div>Loading...</div>;
  }

  const newcompletedexercise = userData?.completedExercises.filter(
    (data) => data.language === somedata.subject
  );

  return (
    <>
      <Head>
        <title>{somedata.heading}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/newlogo1.png" />
      </Head>
      <main>
        <div className={styles.container}>
          <div className={styles.headcont}>
            <div className={styles.mainheading}>{somedata.heading}</div>
          </div>

          <div className={styles.cards1}>
            {reading?.map((data, index) => {
               const completedData = newcompletedexercise?.find(quiz => quiz.exercise.toString() === data.id);
               const completedStyles = completedData ? styles.completed : ''; // Add completed styles
              return (
                <div key={data.quiz} className={`${styles.card1} ${completedStyles}`}>
                  {user.trial && data.id < 3 || user.type === 'all' || !user.trial ?
                   <Link href={`SingleReadingAssignment/${somedata.link2}/${data.id}`} className={styles.link}>
                  {/* {isLocked && (
                    <div className={styles.lockOverlay1}>
                      <FaLock className={styles.lockIcon1} />
                    </div>
                  )} */}
                  <div className={styles.cardflex5}>
                    <div className={styles.info}>
                      <div className={styles.name}>{data.name}</div>
                      <div className={styles.level}>Level: {data.level}</div>
                      <div className={styles.score}>Scrore: {completedData?.score ? completedData?.score : "N/A"}</div>
                    </div>
                    <div className={styles.imgcont}>
                      {/* <Image  src={'/assests/1.png'} width={500} height={500} alt="img" /> */}
                      <IoPlayCircleSharp className={styles.img6}/>
                    </div>
                    </div>
                  </Link>:<div className={styles.locked2}>
                <div className={styles.lockOverlay3}>
                  <FaLock />
                  <p>Locked</p>
                </div>
                  {/* {isLocked && (
                    <div className={styles.lockOverlay1}>
                      <FaLock className={styles.lockIcon1} />
                    </div>
                  )} */}
                  <div className={styles.cardflex5}>
                    <div className={styles.info}>
                      <div className={styles.name}>{data.name}</div>
                      <div className={styles.level}>Level: {data.level}</div>
                    </div>
                    <div className={styles.imgcont}>
                      {/* <Image  src={'/assests/1.png'} width={500} height={500} alt="img" /> */}
                      <IoPlayCircleSharp className={styles.img6}/>
                    </div>
                    </div>
                  </div>}

                </div>
              );
            })}
          </div>

        </div>
      </main>
    </>
  );
}
