import React from 'react'
import Head from 'next/head'
import styles from "../../styles/Languageclub/languageclub.module.css"
import Image from 'next/image'
import Reveal from '../../../components/Reveal'
import dynamic from 'next/dynamic'
import { motion } from 'framer-motion';

const LanguageClub = () => {
  return (
    <>
    <Head>
    <title>Reading Club</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/logo/newlogo1.png" />
  </Head>
  <main>
  <div>

<div className={styles.readingClubContainer}>
      {/* Header Section */}
      <motion.div 
        className={styles.headerSection}
        initial={{ opacity: 0, y: -50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
      >
        <h1>Welcome to the Reading Club</h1>
        <p>Exploring worlds, building connections, and nurturing our love for stories.</p>
      </motion.div>

      {/* Split Content Section */}
      <motion.div 
        className={styles.contentSection}
        initial={{ opacity: 0, x: -100 }}
        whileInView={{ opacity: 1, x: 0 }}
        transition={{ duration: 1 }}
      >
        <div className={styles.textContent}>
          <h2>What Makes Our Club Special?</h2>
          <p>
            One of the most rewarding aspects of our reading club is the sense of community it fosters. Each member brings their unique perspectives, experiences, and insights to the table, enriching our discussions and broadening our understanding of the books we read.
          </p>
          <p>
            Whether it's a heated debate over the moral ambiguity of a character's actions or a shared moment of joy over a beautifully crafted sentence, our club provides a supportive space where everyone's voice is heard and valued. Through our shared love of reading, we form connections that transcend the pages of the books we read, forging friendships and fostering a sense of belonging.
          </p>
        </div>
        <motion.div
          className={styles.imageContent}
          initial={{ scale: 0.8, opacity: 0 }}
          whileInView={{ scale: 1, opacity: 1 }}
          transition={{ duration: 1, delay: 0.5 }}
        >
          <img className={styles.img30} src="/content/reading/1.jpg" alt="Reading Club" />
        </motion.div>
      </motion.div>

      {/* Testimonial Section */}
      {/* <motion.div
        className={styles.testimonialSection}
        initial={{ opacity: 0, y: 50 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
      >
        <h2>What Our Members Say</h2>
        <motion.div
          className={styles.testimonial}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1.2 }}
        >
          <blockquote>
            "This club has transformed the way I engage with literature. The discussions are insightful, and the community is warm and welcoming!"
          </blockquote>
          <p>- A Happy Member</p>
        </motion.div>
      </motion.div> */}

      {/* Call to Action */}
      <motion.div
        className={styles.ctaSection}
        initial={{ opacity: 0, scale: 0.9 }}
        whileInView={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.8 }}
      >
        <h2>Join the Reading Club</h2>
        <p>Ready to dive into a world of books, discussions, and connections?</p>
        <motion.a 
          href="/"
          className={styles.ctaButton}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          Become a Member
        </motion.a>
      </motion.div>
    </div>
    </div>
  </main>
  </>
  )
}

export default dynamic(() => Promise.resolve(LanguageClub), { ssr: false });