import React from 'react'
import styles from "../../styles/Languageclub/languageclub.module.css"
import Image from 'next/image'
import Reveal from '../../../components/Reveal'
import Head from 'next/head'
import { motion } from 'framer-motion';


export default function LanguageClub() {
  return (
    <>
    <Head>
    <title>Writing Club</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/logo/newlogo1.png" />
  </Head>    
  <main>

<div className={styles.readingClubContainer}>
      {/* Header Section */}
      <motion.div 
        className={styles.headerSection}
        initial={{ opacity: 0, y: -50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
      >
        <h1>Welcome to the Writing Club</h1>
        <p>Exploring worlds, building connections, and nurturing our love for stories.</p>
      </motion.div>

      {/* Split Content Section */}
      <motion.div 
        className={styles.contentSection}
        initial={{ opacity: 0, x: -100 }}
        whileInView={{ opacity: 1, x: 0 }}
        transition={{ duration: 1 }}
      >
        <div className={styles.textContent}>
          <h2>What Makes Our Club Special?</h2>
          <p>
          At our writing club, we believe that everyone has a story to tell and that writing is a powerful tool for self-expression, empowerment, and connection. Whether you're a seasoned professional or a novice writer just starting out, our club welcomes writers of all backgrounds, genres, and levels of experience.<br/><br/>So why not join us on our writing journey? Together, we'll explore the boundless possibilities of language and imagination, support each other through the highs and lows of the creative process, and celebrate the transformative power of storytelling in all its forms.
          </p>
          <p>
          One of the most valuable aspects of our writing club is the sense of community it fosters. Writing can often be a solitary and isolating endeavor, but our club provides a supportive network of like-minded individuals who share a passion for storytelling and a commitment to helping each other succeed.
          </p>
        </div>
        <motion.div
          className={styles.imageContent}
          initial={{ scale: 0.8, opacity: 0 }}
          whileInView={{ scale: 1, opacity: 1 }}
          transition={{ duration: 1, delay: 0.5 }}
        >
          <img className={styles.img30} src="/content/writing/1.jpg" alt="Reading Club" />
        </motion.div>
      </motion.div>

      {/* Testimonial Section */}
      <motion.div
        className={styles.testimonialSection}
        initial={{ opacity: 0, y: 50 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
      >
        <h2>What Our Members Say</h2>
        <motion.div
          className={styles.testimonial}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1.2 }}
        >
          <blockquote>
          "The Writing Club has helped me find my voice as a writer. The feedback and support from fellow members have been invaluable."
          </blockquote>
          <p>- A Happy Member</p>
        </motion.div>
      </motion.div>

      {/* Call to Action */}
      <motion.div
        className={styles.ctaSection}
        initial={{ opacity: 0, scale: 0.9 }}
        whileInView={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.8 }}
      >
        <h2>Join the Writing Club</h2>
        <p>Ready to unleash your creativity and share your words with the world?</p>
        <motion.a 
          href="/"
          className={styles.ctaButton}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          Become a Member
        </motion.a>
      </motion.div>
    </div>
    </main>
    </>

  )
}