import Link from 'next/link'
import React from 'react'
import Head from 'next/head'
import styles from "../../styles/quiz/quizpage.module.css"

export default function index() {
  return (
    <>
      <Head>
        <title>Read Now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/newlogo1.png" />
      </Head>
      <main>
      <div className={styles.container}>
        <div className={styles.headcont}><div className={styles.mainheading}>Read Now</div></div>
      

      <div className={styles.maintext}>Explore the beauty of new cultures by mastering Spanish, French, German, or Italian through our engaging lessons. Whether you're a beginner or looking to perfect your fluency, our language courses are designed to guide you at every step.</div>

    <div className={styles.cards}>

      <div className={styles.card}>
        <div className={styles.cardheading}>French Lessons</div>
        <div className={styles.cardtext}>Master the language of art, culture, and diplomacy with our French lessons.</div>
        <Link href='/Readnow/Frenchlessons' className={styles.btn}>Start Learning</Link>
      </div>

      <div className={styles.card}>
        <div className={styles.cardheading}>German Lessons</div>
        <div className={styles.cardtext}>Navigate both casual and formal language settings of Germany with this course.</div>
        <Link href='/Readnow/Germanlessons' className={styles.btn}>Start Learning</Link>
      </div>

      <div className={styles.card}>
        <div className={styles.cardheading}>Spanish Lessons</div>
        <div className={styles.cardtext}>Dive into the vibrant world of Spanish-speaking countries with this course.</div>
        <Link href='/Readnow/Spanishlessons' className={styles.btn}>Start Learning</Link>
      </div>


      {/* <div className={styles.card}>
        <div className={styles.cardheading}>Italian Lessons</div>
        <div className={styles.cardtext}>Learn Italian and embrace the heart of Italy's rich history, cuisine, and fashion.</div>
        <Link href='/Readnow/Italianlessons' className={styles.btn}>Start Learning</Link>
      </div> */}

      </div>
    </div>
      </main>
    </>

  )
}
