import Link from 'next/link'
import React from 'react'
import Head from 'next/head'
import styles from "../../styles/quiz/quizpage.module.css"

export default function index() {
  return (
    <>
      <Head>
        <title>Free Quizzes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/newlogo1.png" />
      </Head>
      <main>
      <div className={styles.container}>
        <div className={styles.headcont}><div className={styles.mainheading}>Free Quizzes</div></div>
      

      <div className={styles.maintext}>Dive into our engaging tests designed to challenge and inspire learners of all levels. Whether you're brushing up on vocabulary, testing your grammar knowledge, or exploring cultural trivia, we've got something for everyone. With a diverse range of topics and interactive formats, our tests are the perfect way to reinforce what you've learned and discover new insights along the way.</div>

    <div className={styles.cards}>

      <div className={styles.card}>
        <div className={styles.cardheading}>French Language</div>
        <div className={styles.cardtext}>Get ready to put your French skills to the test with our exciting range of quizzes.</div>
        <Link href='/QuizTime/FrenchQuizs' className={styles.btn}>Start Test</Link>
      </div>

      <div className={styles.card}>
        <div className={styles.cardheading}>Spanish Language</div>
        <div className={styles.cardtext}>Get ready to put your Spanish skills to the test with our exciting range of quizzes.</div>
        <Link href='/QuizTime/SpanishQuizs' className={styles.btn}>Start Test</Link>
      </div>

      <div className={styles.card}>
        <div className={styles.cardheading}>German Language</div>
        <div className={styles.cardtext}>Get ready to put your German skills to the test with our exciting range of quizzes.</div>
        <Link href='/QuizTime/GermanQuizs' className={styles.btn}>Start Test</Link>
      </div>

      <div className={styles.card}>
        <div className={styles.cardheading}>Italian Language</div>
        <div className={styles.cardtext}>Get ready to put your Italian skills to the test with our exciting range of quizzes.</div>
        <Link href='/QuizTime/ItalianQuizs' className={styles.btn}>Start Test</Link>
      </div>

      {/* <div className={styles.card}>
        <div className={styles.cardheading}>Sanskrit Quiz</div>
        <div className={styles.cardtext}>Get ready to put your Sanskrit skills to the test with our exciting range of quizzes.</div>
        <Link href='/QuizTime/SanskritQuiz' className={styles.btn}>Start Quiz</Link>
      </div> */}

      </div>
    </div>
      </main>
    </>

  )
}
