import Head from 'next/head'
import React from 'react'
import styles from "../../styles/Languageclub/languageclub.module.css"
import Image from 'next/image'
import Reveal from '../../../components/Reveal'

export default function LanguageClub() {
  return (
    <>
      <Head>
        <title>Testimonials</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/newlogo1.png" />
      </Head>
      <main>    
      <div>
    <Reveal>
      <div className={styles.bigicontainer}>
        <div className={styles.headcont}><div className={styles.mainheading}>Testimonials</div></div>
      </div>
    </Reveal>

      <div className={styles.cards23}>

      <div className={styles.cardcontainer23}>
        <div className={styles.card23}>
          <div className={styles.imgcontainer23}>
            <div className={styles.img23}>
              <Image className={styles.img23} src={"/profileimg/6 (10).png"} width={400} height={400} alt="image"/>
            </div>
            <div>
            <div className={styles.name23}>Dyumna</div>
            <div className={styles.boldtext23}>SPANISH FOUNDATION (A1 & A2)</div>
            </div>
          </div>
          <div>
            <div className={styles.description23}>The beginner level Spanish lessons took up a very holistic approach towards understanding the language and to gain the ability to start speaking it a little by the end of the modules. Dominic sir's way of teaching helped me in initiating and engaging in basic conversation in Spanish. Overall, it was a wonderful learning experience.</div>
          </div>
        </div>
        </div>

        <div className={styles.cardcontainer23}>
        <div className={styles.card23}>
          <div className={styles.imgcontainer23}>
          <div className={styles.img23}>
            <Image className={styles.img23} src={"/profileimg/6 (9).png"} width={400} height={400} alt="image"/>
            </div>
            <div>
            <div className={styles.name23}>Nipun Banerjee</div>
            <div className={styles.boldtext23}>SPANISH FOUNDATION (A1 & A2)</div>
            </div>
          </div>
          <div>
            <div className={styles.description23}>The overall content delivery was phenomenal. The level of interaction even in an online session made the whole experience fruitful. The content itself was extremely informative and the most important part of the classes that made it different and effective was the practice of correct pronunciation. That itself is something that is hard to grasp and teach.</div>
          </div>
        </div>
        </div>

        <div className={styles.cardcontainer23}>
        <div className={styles.card23}>
          <div className={styles.imgcontainer23}>
          <div className={styles.img23}>
            <Image className={styles.img23} src={"/profileimg/6 (8).png"} width={400} height={400} alt="image"/>
            </div>
            <div>
            <div className={styles.name23}>Prisha Chhabra</div>
            <div className={styles.boldtext23}>GERMAN FOUNDATION & INTERMEDIATE (A1 - B2)</div>
            </div>
          </div>
          <div>
            <div className={styles.description23}>The 10-day Spanish foundation course with Apriori Education completely changed the way I look at learning a new language. I am thankful to be aware of how enriching, fun and lasting the knowledge of an interesting language like Spanish can be. From the first class till the last, you learn every aspect of its practicality when you come around to speaking it.</div>
          </div>
        </div>
        </div>

        {/* <div className={styles.cardcontainer23}>
        <div className={styles.card23}>
          <div className={styles.imgcontainer23}>
          <div className={styles.img23}>
            <Image className={styles.img23} src={"/profileimg/10 (5).jpg"} width={400} height={400} alt="image"/>
            </div>
            <div>
            <div className={styles.name23}>Priyanka</div>
            <div className={styles.boldtext23}>GERMAN FOUNDATION & INTERMEDIATE (A1 - B2)</div>
            </div>
          </div>
          <div>
            <div className={styles.description23}>The 10-day Spanish foundation course with Apriori Education completely changed the way I look at learning a new language. I am thankful to be aware of how enriching, fun and lasting the knowledge of an interesting language like Spanish can be. From the first class till the last, you learn every aspect of its practicality when you come around to speaking it.</div>
          </div>
        </div>
        </div>

        <div className={styles.cardcontainer23}>
        <div className={styles.card23}>
          <div className={styles.imgcontainer23}>
          <div className={styles.img23}>
            <Image className={styles.img23} src={"/profileimg/10 (4).jpg"} width={400} height={400} alt="image"/>
            </div>
            <div>
            <div className={styles.name23}>Vishaka</div>
            <div className={styles.boldtext23}>GERMAN FOUNDATION & INTERMEDIATE (A1 - B2)</div>
            </div>
          </div>
          <div>
            <div className={styles.description23}>The 10-day Spanish foundation course with Apriori Education completely changed the way I look at learning a new language. I am thankful to be aware of how enriching, fun and lasting the knowledge of an interesting language like Spanish can be. From the first class till the last, you learn every aspect of its practicality when you come around to speaking it.</div>
          </div>
        </div>
        </div>

        <div className={styles.cardcontainer23}>
        <div className={styles.card23}>
          <div className={styles.imgcontainer}>
          <div className={styles.img23}>
            <Image className={styles.img23} src={"/profileimg/10 (3).jpg"} width={400} height={400} alt="image"/>
            </div>
            <div>
            <div className={styles.name23}>Nandini</div>
            <div className={styles.boldtext23}>GERMAN FOUNDATION & INTERMEDIATE (A1 - B2)</div>
            </div>
          </div>
          <div>
            <div className={styles.description23}>The 10-day Spanish foundation course with Apriori Education completely changed the way I look at learning a new language. I am thankful to be aware of how enriching, fun and lasting the knowledge of an interesting language like Spanish can be. From the first class till the last, you learn every aspect of its practicality when you come around to speaking it.</div>
          </div>
        </div>
        </div>

        <div className={styles.cardcontainer23}>
        <div className={styles.card23}>
          <div className={styles.imgcontainer23}>
          <div className={styles.img23}>
            <Image className={styles.img23} src={"/profileimg/10 (2).jpg"} width={400} height={400} alt="image"/>
            </div>
            <div>
            <div className={styles.name23}>Aparna</div>
            <div className={styles.boldtext23}>GERMAN FOUNDATION & INTERMEDIATE (A1 - B2)</div>
            </div>
          </div>
          <div>
            <div className={styles.description23}>The 10-day Spanish foundation course with Apriori Education completely changed the way I look at learning a new language. I am thankful to be aware of how enriching, fun and lasting the knowledge of an interesting language like Spanish can be. From the first class till the last, you learn every aspect of its practicality when you come around to speaking it.</div>
          </div>
        </div>
        </div>

        <div className={styles.cardcontainer23}>
        <div className={styles.card23}>
          <div className={styles.imgcontainer23}>
          <div className={styles.img23}>
            <Image className={styles.img23} src={"/profileimg/10 (6).jpg"} width={400} height={400} alt="image"/>
            </div>
            <div>
            <div className={styles.name23}>Mandika</div>
            <div className={styles.boldtext23}>GERMAN FOUNDATION & INTERMEDIATE (A1 - B2)</div>
            </div>
          </div>
          <div>
            <div className={styles.description23}>The 10-day Spanish foundation course with Apriori Education completely changed the way I look at learning a new language. I am thankful to be aware of how enriching, fun and lasting the knowledge of an interesting language like Spanish can be. From the first class till the last, you learn every aspect of its practicality when you come around to speaking it.</div>
          </div>
        </div>
        </div> */}

      </div>
    </div></main>
    </>

  )
}