import Link from 'next/link';
import React from 'react';
import Head from 'next/head';
import { useSelector } from 'react-redux'; // To access authentication status from Redux
import styles from "../../styles/quiz/quizpage.module.css";

export default function Index() {
  const { user } = useSelector((state) => state.auth);

  const cards = [
        {
          "id": "1",
          "heading": "Lessons",
          "text": "Structured language lessons covering grammar, vocabulary, and usage.",
          "link": "Readnow"
        },
        {
          "id": "2",
          "heading": "Exercises",
          "text": "Interactive activities to reinforce language skills through practice.",
          "link": "Exercise"
        },
        {
          "id": "3",
          "heading": "Conversations",
          "text": "Real-life conversational scenarios to improve speaking and comprehension.",
          "link": "Conversations"
        },
        {
          "id": "4",
          "heading": "Reading Assignments",
          "text": "Text-based tasks designed to enhance reading skills and comprehension.",
          "link": "ReadingAssignments"
        },
        {
          "id": "5",
          "heading": "Listening Assignments",
          "text": "Audio exercises aimed at improving listening comprehension.",
          "link": "ListeningAssignments"
        },
        {
          "id": "6",
          "heading": "Speaking Practice",
          "text": "Exercises focused on developing pronunciation and speaking fluency.",
          "link": "ReadingPractice"
        },
        {
          "id": "7",
          "heading": "Writing Practice",
          "text": "Activities to improve writing skills through structured tasks.",
          "link": "WritingPractice"
        },
        {
          "id": "8",
          "heading": "Practice Test",
          "text": "Quizzes to test and assess language proficiency and knowledge.",
          "link": "TestPrep"
        },
]

  return (
    <>
      <Head>
        <title>Welcome {user?.name}!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/newlogo1.png" />
      </Head>
      <main>
        <div className={styles.container}>
          <div className={styles.headcont}>
            <div className={styles.mainheading}>Welcome {user?.name}!</div>
          </div>

          <div className={styles.maintext}>
            Explore the beauty of new cultures by mastering Spanish, French, or German through our engaging lessons. Whether you're a beginner or looking to perfect your fluency, our language courses are designed to guide you at every step.
          </div>

          <div className={styles.cards}>
            {cards.map((card) => (
              <div
                key={card?.id}
                className={`${styles.card}`}
              >
                <div className={styles.cardheading}>{card?.heading}</div>
                <div className={styles.cardtext}>{card?.text}</div>
                  <Link href={`/${card?.link}`} className={styles.btn}>
                    Start Learning
                  </Link>
              </div>
            ))}
            {user?.type === 'all' && <div
                key={'9'}
                className={`${styles.card}`}
              >
                 <div className={styles.cardheading}>Admin Panel</div>
                <div className={styles.cardtext}>A management interface for controlling content, users, and course settings.</div>
                  <Link href={'/AdminPanel'} className={styles.btn}>
                    Start Learning
                  </Link>
              </div>}
          </div>
        </div>
      </main>
    </>
  );
}
