import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import { cards } from '../../Data/Routes/Conversations'
import styles from '../../styles/quiz/conversation.module.css';
import Image from 'next/image';
import Link from 'next/link';
import { FaLock } from 'react-icons/fa'; // Import a lock icon
import { useRouter } from 'next/router';
import { useSelector } from 'react-redux';

export default function FrenchQuizes() {
  const { isAuthenticated, user } = useSelector((state) => state.auth); // Access authentication status
  const [isClient, setIsClient] = useState(false);
    const [convoData, setconvoData] = useState(null);

      const router = useRouter();
      const { id } = router.query; // Get the dynamic `id` from the route
    
      const somedata = cards.find((data) => data.link === id);

  useEffect(() => {
    setIsClient(true); // Set to true when client-side is ready

    if (somedata) {
      // Dynamically import the lesson data
      import(`../../Data/Conversationdata/${somedata.data}`)
        .then((module) => setconvoData(module.youdata))
        .catch((error) => console.error('Error loading lesson data:', error));
    }
  }, [somedata]);



  if (!isClient || !somedata) {
    // Optionally return a loader or handle invalid `id`
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>{somedata?.heading}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/newlogo1.png" />
      </Head>
      <main>
        <div className={styles.container1}>
          <div className={styles.headcont}>
            <div className={styles.mainheading}>{somedata?.heading}</div>
          </div>

          <div className={styles.container}>
          {convoData?.map((data, index) => {
      return (
        <div key={data.id} className={styles.videocontainer}>

{user.trial && data.id < 3 || user.type === 'all' || !user.trial ? (
              <Link className={styles.link} href={`/Conversations/SingleConversation/${somedata.link2}/${data.id}`}>
                <div className={styles.imgcont}>
                  <div className={styles.logocont}>
                    <Image
                      className={styles.imagelogo}
                      src={'/youtube/youtube.png'}
                      width={400}
                      height={180}
                      alt='image'
                    />
                  </div>
                  <Image className={styles.image} src={data.url} width={400} height={180} alt={data.title} />
                </div>
                <div>
                  <h3 className={styles.title}>{data.title}</h3>
                  <p className={styles.desc}>{data.desc.slice(0, 100)}...</p>
                </div>
              </Link>
            ) : (
              <div className={styles.locked}>
                <div className={styles.lockOverlay}>
                  <FaLock />
                  <p>Locked</p>
                </div>
                <div className={styles.imgcont}>
                  <div className={styles.logocont}>
                    <Image
                      className={styles.imagelogo}
                      src={'/youtube/youtube.png'}
                      width={400}
                      height={180}
                      alt='image'
                    />
                  </div>
                  <Image className={styles.image} src={data.url} width={400} height={180} alt={data.title} />
                </div>
                <div>
                  <h3 className={styles.title}>{data.title}</h3>
                  <p className={styles.desc}>{data.desc.slice(0, 100)}...</p>
                </div>
              </div>
            )}

      </div>
      )
    })}
          </div>
        </div>
      </main>
    </>
  );
}
