import Head from 'next/head'
import styles from '../../styles/Languageclub/languageclub.module.css'
import Image from 'next/image'
import Reveal from '../../../components/Reveal'
import Link from 'next/link'

const index = () => {

  const data = [
    {
      id: 1,
      title: "Readers' Salon",
      date: "Sat, 26th Nov 2023 ",
      url: "/events/Podcast Insta.jpg",
    },
    {
      id: 2,
      title: "Halloween Party",
      date: "31st Oct 2023",
      url: "/events/October 31,2023.jpg",
    },
    {
      id: 3,
      title: "Young Poet Award 2023",
      date: "TBD",
      url: "/events/YoungPoetAward.png",
    },
  ];

  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/newlogo1.png" />
      </Head>
      <main>
      <div>      
      <div className={styles.topcontainer}>
        <div className={styles.tint}/>
        <Image className={styles.img} src={'/content/25.jpg'} width={2400} height={1400} alt="img"/>
          <div className={styles.textcontainer}>
          <Reveal>
            <div className={styles.heading1}>Events</div>
          </Reveal>
          <Reveal>
            <div className={styles.text1}>Our events are designed to enhance the learning experience and outcomes of our learners and educators, as well as to provide them with opportunities to network, collaborate, and grow.</div>
          </Reveal>
          </div>
      </div>
      <div className={styles.eventscards}>
      {data.map((data) => (
        <Reveal>
        <Link href={`/Event/${data.id}`} className={styles.eventcard}>
          <div className={styles.eventcardimgcontainer}>
            <Image className={styles.eventcardimg} src={data.url} width={400} height={400} alt="image"/>
          </div>
          <div className={styles.eventtopic}>Date - {data.date}</div>
          <div className={styles.eventtext}>{data.title}</div>
        </Link>
      </Reveal>
      ))}
      </div>
    </div>
      </main>
    </>

  )
}

export default index