import Head from 'next/head'
import React from 'react'
import styles from '../../styles/testprep.module.css'
import Image from 'next/image'
import { FaLock } from 'react-icons/fa'; // Import a lock icon
import { useSelector } from 'react-redux'; // To access authentication status from Redux
import Link from 'next/link';

export default function index() {

  const { isAuthenticated } = useSelector((state) => state.auth); // Access authentication status

  const data = [{
    url:'/Testprep/1.jpg',
    name:'Free Trial',
    text:'Try all formats of the test',
    link:'/TrialTest',
  },
  {
    url:'/Testprep/2.jpg',
    name:'Fill in the blanks',
    text:'Fill in the blanks with the correct answers',
    link:'/TrialTest',
  },
  {
    url:'/Testprep/3.jpg',
    name:'Jumbled Words',
    text:'Reorder words to get the correct answers',
    link:'/TrialTest',
  },
  {
    url:'/Testprep/4.jpg',
    name:'MCQs',
    text:'Select the correct answers from given options',
    link:'/TrialTest',
  },
  {
    url:'/Testprep/5.jpg',
    name:'Click on the correct answer',
    text:'Highlight the incorrect words to get the correct answer',
    link:'/TrialTest',
  },
  {
    url:'/Testprep/6.jpg',
    name:'Drag and drop to the correct box',
    text:'Select missing words to get the correct answer',
    link:'/TrialTest',
  }]

  return (
    <>      
    <Head>
    <title>Practice Test</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/logo/newlogo1.png" />
  </Head>
  <main>
  <div className={styles.container}>
    <div className={styles.headcont}><div className={styles.mainheading}>Practice Test</div></div>

    <div className={styles.cards}>

       {data.map((data,index)=>{ 
         const isLocked = !isAuthenticated && index > 0;
              return (<div key={data.name} className={`${styles.card} ${isLocked ? styles.locked : ''}`}>
            <Link href={'/TrialTest'} className={styles.link}>
            <div className={styles.imgcont}>
              <Image className={styles.img} width={400} height={300} src={data.url} alt="image"/>
            </div>
            <div className={styles.info}>
              <div className={styles.name}>{data.name}</div>
              <div className={styles.text}>{data.text}</div>
            </div>
            </Link>
            {isLocked && (
                    <div className={styles.lockOverlay}>
                      <FaLock className={styles.lockIcon} />
                    </div>
                  )}
                </div>
        )})}

    </div>
 </div>
 </main>
</>
  )
}
