import React from 'react'
import Head from 'next/head'
import styles from "../../styles/Languageclub/languageclub.module.css"
import Image from 'next/image'
import Reveal from '../../../components/Reveal'
import { motion } from 'framer-motion';


export default function LanguageClub() {
  return (
    <>
      <Head>
        <title>Olympiad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/newlogo1.png" />
      </Head>
      <main>

    <div className={styles.readingClubContainer}>
      {/* Header Section */}
      <motion.div 
        className={styles.headerSection}
        initial={{ opacity: 0, y: -50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
      >
        <h1>Welcome to the Olympiad Club</h1>
        <p>Challenge yourself, excel in academics, and prepare for the world stage.</p>
      </motion.div>

      {/* Split Content Section */}
      <motion.div 
        className={styles.contentSection}
        initial={{ opacity: 0, x: -100 }}
        whileInView={{ opacity: 1, x: 0 }}
        transition={{ duration: 1 }}
      >
        <div className={styles.textContent}>
          <h2>Why Participate in Olympiads?</h2>
          <p>
          Olympiads are a gateway to international academic recognition. Our Olympiads Club provides a platform for students to prepare for various national and international competitions in math, science, technology, and more.<br/><br/>Through rigorous practice, peer learning, and expert guidance, members of our club sharpen their analytical thinking, problem-solving abilities, and subject knowledge. Olympiads foster not only academic excellence but also a sense of accomplishment and intellectual curiosity.
          </p>
          <p>
          An Olympiad Club is an exceptional platform for nurturing intellectual curiosity, critical thinking, and problem-solving skills among students. Our club is dedicated to preparing students for various academic Olympiad competitions, ranging from mathematics and science to literature and history.
          </p>
        </div>
        <motion.div
          className={styles.imageContent}
          initial={{ scale: 0.8, opacity: 0 }}
          whileInView={{ scale: 1, opacity: 1 }}
          transition={{ duration: 1, delay: 0.5 }}
        >
          <img className={styles.img30} src="/content/8.jpg" alt="Reading Club" />
        </motion.div>
      </motion.div>

      {/* Testimonial Section */}
      <motion.div
        className={styles.testimonialSection}
        initial={{ opacity: 0, y: 50 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
      >
        <h2>What Our Members Say</h2>
        <motion.div
          className={styles.testimonial}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1.2 }}
        >
          <blockquote>
          "The Writing Club has helped me find my voice as a writer. The feedback and support from fellow members have been invaluable."
          </blockquote>
          <p>- A Happy Member</p>
        </motion.div>
      </motion.div>

      {/* Call to Action */}
      <motion.div
        className={styles.ctaSection}
        initial={{ opacity: 0, scale: 0.9 }}
        whileInView={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.8 }}
      >
        <h2>Join the Writing Club</h2>
        <p>Ready to unleash your creativity and share your words with the world?</p>
        <motion.a 
          href="/"
          className={styles.ctaButton}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          Become a Member
        </motion.a>
      </motion.div>
    </div>
      </main>
    </>

  )
}