const fs=require("fs");const path=require("path");const {spawnSync}=require("child_process");const root=path.join(__dirname,"..");const fail=[];const exists=p=>fs.existsSync(path.join(root,p));const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const required=["src/components/Reasoning/ReasoningStageViews.js","src/Data/Reasoning/curriculum.js","src/Data/Reasoning/canonicalQuestionSchema.js","scripts/syncReasoningQuestionBanks.js","scripts/testReasoningQuestionBankSync.js","scripts/checkReasoningQuestionBankDrift.js","scripts/testReasoningCanonicalRoundTrip.js","src/Data/Reasoning/questionBank.js","src/Data/Reasoning/questionBankStage1Extensions.js","src/Data/Reasoning/questionBankStage2.js","src/Data/Reasoning/questionBankStage3.js","src/Data/Reasoning/stage3QuestionCalibration.js","src/Data/Reasoning/stage3MissingCalibration.js","src/Data/Reasoning/stage3CompleteCalibration.js","src/Data/Reasoning/reasoningOptionQuality.js","src/Data/Reasoning/stage3Modules.js","src/Data/Reasoning/questionBankStage4.js","src/Data/Reasoning/questionBankStage5.js","src/Data/Reasoning/questionBankStage6.js","src/Data/Reasoning/level2Stage1Activities.js","src/Data/Reasoning/level2Stage1Modules.js","src/Data/Reasoning/questionBankLevel2Stage1.js","src/Data/Reasoning/stage1QuestionCalibration.js","src/Data/Reasoning/stage2QuestionCalibration.js","src/Data/Reasoning/stage4Modules.js","src/Data/Reasoning/stage4Activities.js","src/Data/Reasoning/stage5Modules.js","src/Data/Reasoning/stage5Activities.js","src/Data/Reasoning/stage6Modules.js","src/Data/Reasoning/stage6Activities.js"];
required.forEach(p=>{if(!exists(p))fail.push(`Missing required Reasoning file: ${p}`)});
function checkSyntax(p){const r=spawnSync(process.execPath,["--check",path.join(root,p)],{encoding:"utf8"});if(r.status!==0)fail.push(`JavaScript syntax error in ${p}: ${(r.stderr||r.stdout||"unknown error").replace(/\s+/g," ").trim()}`)}
for(const p of required.filter(p=>/\.js$/.test(p)))if(exists(p))checkSyntax(p);
function resolveImport(fromFile,imp){const base=imp.startsWith("@/")?path.join(root,"src",imp.slice(2)):path.resolve(path.dirname(fromFile),imp);return [base,`${base}.js`,`${base}.jsx`,`${base}.json`,path.join(base,"index.js"),path.join(base,"index.jsx")].some(fs.existsSync)}
function scanImports(dir){if(!exists(dir))return;for(const name of fs.readdirSync(path.join(root,dir))){const rel=path.join(dir,name),full=path.join(root,rel);if(fs.statSync(full).isDirectory())scanImports(rel);else if(/\.(js|jsx)$/.test(name)){const text=read(rel),re=/\bfrom\s*["']([^"']+)["']/g;let m;while((m=re.exec(text)))if((m[1].startsWith(".")||m[1].startsWith("@/"))&&!resolveImport(full,m[1]))fail.push(`Unresolved import: ${rel} -> ${m[1]}`)}}}scanImports("src/pages/Reasoning");
function clean(source){return source.replace(/^import[^;]+;\s*/gm,"").replace(/\bexport\s+(?=(?:const|function|let|var)\b)/g,"")}
function evaluate(files,names){try{return new Function(files.map(read).map(clean).join("\n")+`\nreturn {${names.map(n=>`${n}:typeof ${n}!=="undefined"?${n}:null`).join(",")}};`)()}catch(e){fail.push(`Reasoning calibration could not be evaluated: ${e.message}`);return{}}}
const banks=[["src/Data/Reasoning/questionBank.js","REASONING_QUESTION_BANK"],["src/Data/Reasoning/questionBankStage1Extensions.js","STAGE1_EXTENSION_QUESTIONS"],["src/Data/Reasoning/questionBankStage2.js","STAGE2_QUESTIONS"],["src/Data/Reasoning/questionBankStage3.js","STAGE3_QUESTIONS"],["src/Data/Reasoning/questionBankStage4.js","questions"],["src/Data/Reasoning/questionBankStage5.js","STAGE5_QUESTION_BANK"],["src/Data/Reasoning/questionBankStage6.js","STAGE6_QUESTION_BANK"],["src/Data/Reasoning/questionBankLevel2Stage1.js","LEVEL2_STAGE1_QUESTION_BANK"]];let all=[];for(const [p,n] of banks){if(!exists(p))continue;const d=evaluate([p],[n])[n];if(!Array.isArray(d)||!d.length)fail.push(`Question bank is empty or unavailable: ${p}`);else all.push(...d.map(q=>({...q,__file:p})))}const ids=all.map(q=>q.id).filter(Boolean);if(new Set(ids).size!==ids.length)fail.push("Duplicate Reasoning question IDs detected across audited banks.");for(const q of all)if(!q.id||!q.activityId||!q.question||!Array.isArray(q.options)||q.options.length!==4||new Set(q.options).size!==4||!q.options.includes(q.answer))fail.push(`Malformed question record: ${q.id||"unknown"}`);
const activityPath="src/Data/Reasoning/activities.js",qualityPath="src/Data/Reasoning/reasoningOptionQuality.js",existingPath="src/Data/Reasoning/stage3QuestionCalibration.js",missingPath="src/Data/Reasoning/stage3MissingCalibration.js";
if([activityPath,qualityPath,existingPath,missingPath].every(exists)){const activities=evaluate([activityPath],["REASONING_ACTIVITIES"]).REASONING_ACTIVITIES||[];const existingRuntime=evaluate([qualityPath,existingPath],["getStage3CalibratedQuestions"]);const missingRuntime=evaluate([qualityPath,missingPath],["getStage3MissingCalibratedQuestions"]);const acts=activities.filter(a=>a?.levelId==="L1"&&a?.stageId==="S3");const quant=acts.filter(a=>a.track==="quantitative"),verbal=acts.filter(a=>a.track==="verbal");if(acts.length!==20)fail.push(`Stage 3 activity structure invalid: expected 20 Level 1 activities, found ${acts.length}.`);if(quant.length!==10||verbal.length!==10)fail.push(`Stage 3 track structure invalid: expected 10 Quantitative and 10 Verbal activities, found ${quant.length} Quantitative and ${verbal.length} Verbal.`);const delivered=[];for(const a of acts){let qs=[];let existing=[];try{existing=existingRuntime.getStage3CalibratedQuestions(a.id)||[]}catch(e){existing=[]}if(existing.length>=10){qs=existing}else{try{qs=missingRuntime.getStage3MissingCalibratedQuestions(a.id)||[]}catch(e){qs=[];fail.push(`Stage 3 fallback calibration failed for ${a.id}: ${e.message}`)}}if(qs.length!==10)fail.push(`Stage 3 ${a.id}: expected exactly 10 delivered questions, found ${qs.length}.`);const ids2=qs.map(q=>q.id);if(new Set(ids2).size!==ids2.length)fail.push(`Stage 3 ${a.id}: duplicate delivered question IDs.`);for(const q of qs){if(q.levelId!=="L1"||q.stageId!=="S3"||q.activityId!==a.id)fail.push(`Stage 3 metadata mismatch: ${q.id||"unknown"} -> ${a.id}`);if(!["computation","computationReasoning","textReasoning"].includes(q.contentMode)||!q.contentModeLabel||!q.contentModeDescription)fail.push(`Stage 3 ${q.id}: invalid content-mode metadata.`);if(!Array.isArray(q.options)||q.options.length!==4||new Set(q.options).size!==4||!q.options.includes(q.answer))fail.push(`Stage 3 ${q.id}: invalid options.`);if(q.optionQuality?.lengthCueDetected)fail.push(`Stage 3 ${q.id}: answer-length cue remains.`)}delivered.push(...qs)}if(delivered.length!==200)fail.push(`Stage 3 delivered question total invalid: expected 200, found ${delivered.length}.`);if(new Set(delivered.map(q=>q.id)).size!==delivered.length)fail.push("Stage 3 delivered question IDs are not globally unique.");const badHalf=acts.filter(a=>!a.id.includes("-EXP-")&&!a.id.includes("-EXT-"));if(badHalf.length)fail.push(`Stage 3 activities missing Explore/Extend convention: ${badHalf.map(a=>a.id).join(", ")}`)}
function evaluateWithDependencies(file,names,dependencies){try{const keys=Object.keys(dependencies);const returnSource="\nreturn {"+names.map(n=>n+":typeof "+n+"!==\"undefined\"?"+n+":null").join(",")+"};";return new Function(...keys,clean(read(file))+returnSource)(...keys.map(k=>dependencies[k]));}catch(e){fail.push("Reasoning calibration could not be evaluated: "+e.message);return {};}}
const stage2Activities=evaluate(["src/Data/Reasoning/activities.js"],["REASONING_ACTIVITIES"]).REASONING_ACTIVITIES||[];
const stage2Modules=evaluate(["src/Data/Reasoning/stage2Modules.js"],["STAGE2_MODULES"]).STAGE2_MODULES||{};
const stage2Acts=stage2Activities.filter(a=>a.levelId==="L1"&&a.stageId==="S2");
const stage2Expanded=evaluate(["src/Data/Reasoning/stage2QuestionExpansion.js"],["getStage2ExpandedQuestionsForActivity"]).getStage2ExpandedQuestionsForActivity;
const stage2Elevated=evaluate(["src/Data/Reasoning/stage2ElevatedComputationBank.js"],["getStage2ElevatedComputationQuestions"]).getStage2ElevatedComputationQuestions;
const stage2Questions=evaluate(["src/Data/Reasoning/questionBankStage2.js"],["STAGE2_QUESTIONS"]).STAGE2_QUESTIONS;
const stage2Options=evaluate(["src/Data/Reasoning/reasoningOptionQuality.js"],["prepareReasoningQuestionSet"]).prepareReasoningQuestionSet;
const stage2Calibrated=evaluateWithDependencies("src/Data/Reasoning/stage2QuestionCalibration.js",["getStage2CalibratedQuestions"],{STAGE2_QUESTIONS:stage2Questions,getStage2ExpandedQuestionsForActivity:stage2Expanded,getStage2ElevatedComputationQuestions:stage2Elevated,prepareReasoningQuestionSet:stage2Options}).getStage2CalibratedQuestions;
for(const track of ["quantitative","verbal"]){
 const acts=stage2Acts.filter(a=>a.track===track), explore=acts.filter(a=>String(a.half||"").toLowerCase()==="explore"), extend=acts.filter(a=>String(a.half||"").toLowerCase()==="extend");
 if(explore.length<5||extend.length<3||acts.length<8)fail.push("Stage 2 "+track+": expected at least 5 Explore + 3 Extend + 8 total; found "+explore.length+"/"+extend.length+"/"+acts.length+".");
 const mods=stage2Modules[track]||[], refs=mods.flatMap(m=>m.activityIds||[]);
 if(mods.length!==5||refs.length!==8||new Set(refs).size!==8)fail.push("Stage 2 "+track+": existing five-module structure must map exactly 8 distinct activities after reconciliation.");
 for(const a of acts){
  let qs=[];try{qs=stage2Calibrated?stage2Calibrated(a.id):[];}catch(e){fail.push("Stage 2 calibration failed for "+a.id+": "+e.message);}
  if(qs.length!==10)fail.push("Stage 2 "+a.id+": expected exactly 10 delivered questions, found "+qs.length+".");
  const ids=qs.map(q=>q.id);if(new Set(ids).size!==ids.length)fail.push("Stage 2 "+a.id+": duplicate delivered question IDs.");
  for(const q of qs){
   const qTrack=q.track||a.track;const qStage=q.stageId||"S2";const qHalf=String(q.half||"").toLowerCase();const expectedHalf=String(a.half||"").toLowerCase();if(q.levelId!=="L1"||qStage!=="S2"||q.activityId!==a.id||qTrack!==a.track||(qHalf&&qHalf.slice(0,3)!==expectedHalf.slice(0,3)))fail.push("Stage 2 mapping mismatch: "+(q.id||"unknown")+" -> "+a.id+".");
   if(!q.contentMode||!q.contentModeLabel||!q.contentModeDescription)fail.push("Stage 2 "+(q.id||"unknown")+": missing content-mode metadata.");
   if(!Array.isArray(q.options)||q.options.length!==4||new Set(q.options).size!==4||!q.options.includes(q.answer))fail.push("Stage 2 "+(q.id||"unknown")+": invalid options/answer.");
   if(q.optionQuality?.lengthCueDetected)fail.push("Stage 2 "+q.id+": answer-length cue remains.");
  }
 }
}
if(stage2Acts.length<16)fail.push("Stage 2 total activity count invalid: expected at least 16 across both tracks, found "+stage2Acts.length+".");
if(!stage2Calibrated)fail.push("Stage 2 calibration runtime could not be constructed.");
const universalStageDashboardPages=[
["src/pages/Reasoning/Quantitative/Dashboard/Stage2/index.js","/Reasoning/Quantitative/Dashboard/Stage2"],["src/pages/Reasoning/Quantitative/Dashboard/Stage3/index.js","/Reasoning/Quantitative/Dashboard/Stage3"],["src/pages/Reasoning/Quantitative/Dashboard/Stage4/index.js","/Reasoning/Quantitative/Dashboard/Stage4"],["src/pages/Reasoning/Quantitative/Dashboard/Stage5/index.js","/Reasoning/Quantitative/Dashboard/Stage5"],["src/pages/Reasoning/Quantitative/Dashboard/Stage6/index.js","/Reasoning/Quantitative/Dashboard/Stage6"],
["src/pages/Reasoning/Verbal/Dashboard/Stage2/index.js","/Reasoning/Verbal/Dashboard/Stage2"],["src/pages/Reasoning/Verbal/Dashboard/Stage3/index.js","/Reasoning/Verbal/Dashboard/Stage3"],["src/pages/Reasoning/Verbal/Dashboard/Stage4/index.js","/Reasoning/Verbal/Dashboard/Stage4"],["src/pages/Reasoning/Verbal/Dashboard/Stage5/index.js","/Reasoning/Verbal/Dashboard/Stage5"],["src/pages/Reasoning/Verbal/Dashboard/Stage6/index.js","/Reasoning/Verbal/Dashboard/Stage6"],
["src/pages/Reasoning/Quantitative/Dashboard/Stage1L2/index.js","/Reasoning/Quantitative/Dashboard/Stage1L2"],["src/pages/Reasoning/Verbal/Dashboard/Stage1L2/index.js","/Reasoning/Verbal/Dashboard/Stage1L2"]];
const universalStageModulePages=[
["src/pages/Reasoning/Quantitative/Dashboard/Stage2/[moduleId].js","/Reasoning/Quantitative/Dashboard/Stage2"],["src/pages/Reasoning/Quantitative/Dashboard/Stage3/[moduleId].js","/Reasoning/Quantitative/Dashboard/Stage3"],["src/pages/Reasoning/Quantitative/Dashboard/Stage4/[moduleId].js","/Reasoning/Quantitative/Dashboard/Stage4"],["src/pages/Reasoning/Quantitative/Dashboard/Stage5/[moduleId].js","/Reasoning/Quantitative/Dashboard/Stage5"],["src/pages/Reasoning/Quantitative/Dashboard/Stage6/[moduleId].js","/Reasoning/Quantitative/Dashboard/Stage6"],
["src/pages/Reasoning/Verbal/Dashboard/Stage2/[moduleId].js","/Reasoning/Verbal/Dashboard/Stage2"],["src/pages/Reasoning/Verbal/Dashboard/Stage3/[moduleId].js","/Reasoning/Verbal/Dashboard/Stage3"],["src/pages/Reasoning/Verbal/Dashboard/Stage4/[moduleId].js","/Reasoning/Verbal/Dashboard/Stage4"],["src/pages/Reasoning/Verbal/Dashboard/Stage5/[moduleId].js","/Reasoning/Verbal/Dashboard/Stage5"],["src/pages/Reasoning/Verbal/Dashboard/Stage6/[moduleId].js","/Reasoning/Verbal/Dashboard/Stage6"],
["src/pages/Reasoning/Quantitative/Dashboard/Stage1L2/[moduleId].js","/Reasoning/Quantitative/Dashboard/Stage1L2"],["src/pages/Reasoning/Verbal/Dashboard/Stage1L2/[moduleId].js","/Reasoning/Verbal/Dashboard/Stage1L2"]];
for(const [file,route] of universalStageDashboardPages){if(!exists(file))fail.push("Missing universal stage dashboard: "+file);else{const source=read(file);if(!source.includes("ReasoningStageDashboard"))fail.push("Stage 1 UI invariant violated: "+file);if(!source.includes("stagePath=\""+route+"\""))fail.push("Stage route invariant violated: "+file+" -> "+route);}}
for(const [file,route] of universalStageModulePages){if(!exists(file))fail.push("Missing universal module page: "+file);else{const source=read(file);if(!source.includes("ReasoningModulePage"))fail.push("Stage 1 UI invariant violated: "+file);if(!source.includes("stagePath=\""+route+"\""))fail.push("Module route invariant violated: "+file+" -> "+route);}}
if(fail.length){console.error("Reasoning build validation failed:\n- "+fail.join("\n- "));process.exit(1)}console.log("Reasoning build validation passed: required files, syntax, imports, canonical schema, question-bank structure, complete Stage 3 activity mappings and 200-question Stage 3 delivery are valid.");