const fs=require("fs");const path=require("path");const {spawnSync}=require("child_process");const root=path.join(__dirname,"..");const fail=[];const warn=[];const exists=p=>fs.existsSync(path.join(root,p));const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const required=["src/Data/Reasoning/curriculum.js","src/Data/Reasoning/questionBank.js","src/Data/Reasoning/questionBankStage1Extensions.js","src/Data/Reasoning/questionBankStage2.js","src/Data/Reasoning/questionBankStage3.js","src/Data/Reasoning/questionBankStage4.js","src/Data/Reasoning/questionBankStage5.js","src/Data/Reasoning/questionBankStage6.js","src/Data/Reasoning/level2Stage1Activities.js","src/Data/Reasoning/level2Stage1Modules.js","src/Data/Reasoning/questionBankLevel2Stage1.js","src/Data/Reasoning/stage3Modules.js","src/Data/Reasoning/stage4Modules.js","src/Data/Reasoning/stage4Activities.js","src/Data/Reasoning/stage5Modules.js","src/Data/Reasoning/stage5Activities.js","src/Data/Reasoning/stage6Modules.js","src/Data/Reasoning/stage6Activities.js"];
required.forEach(p=>{if(!exists(p))fail.push(`Missing required Reasoning file: ${p}`)});
function checkSyntax(p){const r=spawnSync(process.execPath,["--check",path.join(root,p)],{encoding:"utf8"});if(r.status!==0)fail.push(`JavaScript syntax error in ${p}: ${(r.stderr||r.stdout||"unknown error").replace(/\s+/g," ").trim()})`)}
for(const p of ["src/Data/Reasoning/questionBank.js","src/Data/Reasoning/questionBankStage1Extensions.js","src/Data/Reasoning/questionBankStage2.js","src/Data/Reasoning/questionBankStage3.js","src/Data/Reasoning/questionBankStage4.js","src/Data/Reasoning/questionBankStage5.js","src/Data/Reasoning/questionBankStage6.js","src/Data/Reasoning/questionBankLevel2Stage1.js"]){if(exists(p))checkSyntax(p)}
function resolveImport(fromFile,imp){const base=imp.startsWith("@/")?path.join(root,"src",imp.slice(2)):path.resolve(path.dirname(fromFile),imp);return [base,`${base}.js`,`${base}.jsx`,`${base}.json`,path.join(base,"index.js"),path.join(base,"index.jsx")].some(fs.existsSync)}
function scanImports(dir){if(!exists(dir))return;for(const name of fs.readdirSync(path.join(root,dir))){const rel=path.join(dir,name),full=path.join(root,rel);if(fs.statSync(full).isDirectory())scanImports(rel);else if(/\.(js|jsx)$/.test(name)){const text=read(rel),re=/\bfrom\s*["']([^"']+)["']/g;let m;while((m=re.exec(text)))if((m[1].startsWith(".")||m[1].startsWith("@/"))&&!resolveImport(full,m[1]))fail.push(`Unresolved import: ${rel} -> ${m[1]}`)}}}scanImports("src/pages/Reasoning");
for(const track of ["Quantitative","Verbal"])for(const stage of [1,2,3,4,5,6]){const dir=`src/pages/Reasoning/${track}/Dashboard/Stage${stage}`;if(exists(`${dir}.js`)&&exists(`${dir}/index.js`))fail.push(`Duplicate Next.js route: ${dir}.js and ${dir}/index.js`)}
function clean(source){return source.replace(/^import[^;]+;\s*/gm,"").replace(/\bexport\s+(?=(?:const|function|let|var)\b)/g,"")}
function evaluate(p,names){if(!exists(p))return{};try{return new Function(`${clean(read(p))}\nreturn {${names.map(n=>`${n}:typeof ${n}!=="undefined"?${n}:null`).join(",")}};`)()}catch(e){fail.push(`Question bank could not be evaluated: ${p}: ${e.message}`);return{}}}
const banks=[["src/Data/Reasoning/questionBank.js",["REASONING_QUESTION_BANK"]],["src/Data/Reasoning/questionBankStage1Extensions.js",["STAGE1_EXTENSION_QUESTIONS"]],["src/Data/Reasoning/questionBankStage2.js",["STAGE2_QUESTIONS"]],["src/Data/Reasoning/questionBankStage3.js",["STAGE3_QUESTIONS"]],["src/Data/Reasoning/questionBankStage4.js",["questions"]],["src/Data/Reasoning/questionBankStage5.js",["STAGE5_QUESTION_BANK"]],["src/Data/Reasoning/questionBankStage6.js",["STAGE6_QUESTION_BANK"]],["src/Data/Reasoning/questionBankLevel2Stage1.js",["LEVEL2_STAGE1_QUESTION_BANK"]]];
let all=[];for(const [p,names] of banks){const data=evaluate(p,names);for(const n of names){const bank=data[n];if(!Array.isArray(bank)){fail.push(`Expected question array ${n} was not found in ${p}`);continue}if(bank.length===0)fail.push(`Question bank is empty: ${p}`);all.push(...bank.map(q=>({...q,__file:p})))} }
const ids=all.map(q=>q.id).filter(Boolean);if(new Set(ids).size!==ids.length)fail.push("Duplicate Reasoning question IDs detected across the audited banks.");
for(const q of all)if(!q.id||!q.activityId||!q.question||!Array.isArray(q.options)||q.options.length!==4||!q.options.includes(q.answer))fail.push(`Malformed question record: ${q.id||"unknown"}`);
function textOnly(q){return q.options.every(o=>typeof o==="string"&&!/[0-9₹$€£%]/.test(o))}
const eligible=all.filter(textOnly);const longestCorrect=eligible.filter(q=>{const lens=q.options.map(o=>o.trim().length),max=Math.max(...lens);return q.answer.trim().length===max}).length;const longestRate=eligible.length?longestCorrect/eligible.length:0;if(eligible.length&&(longestRate<0.20||longestRate>0.40))warn.push(`Answer-length audit: longest option is correct in ${(longestRate*100).toFixed(1)}% of eligible text-only questions; target is approximately 30%.`);
const caseIssues=eligible.filter(q=>{const starts=q.options.map(o=>o.trim()).filter(Boolean).map(o=>/^[a-z]/.test(o));return starts.some(Boolean)&&starts.some(v=>!v)});if(caseIssues.length)warn.push(`Capitalization audit: ${caseIssues.length} text-only questions have mixed lower/upper-case option starts and require review.`);
const positionCounts=[0,0,0,0];for(const q of all){const i=q.options.indexOf(q.answer);if(i>=0)positionCounts[i]++}if(all.length){const max=Math.max(...positionCounts),min=Math.min(...positionCounts);if(max-min>Math.ceil(all.length*0.20))warn.push(`Answer-position audit: option positions are uneven (${positionCounts.join(", ")}); review for predictable answer placement.`)}
if(warn.length)console.warn("Reasoning assessment-quality audit warnings:\n- "+warn.join("\n- "));
if(fail.length){console.error("Reasoning build validation failed:\n- "+fail.join("\n- "));process.exit(1)}console.log(`Reasoning build validation passed: required files, imports/routes, syntax, non-empty banks, question structure and stable IDs are valid. Assessment-quality audit reviewed ${eligible.length} text-only questions.`);
