import Head from "next/head";
import Link from "next/link";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
import { useEffect,useState } from "react";
import { STAGE2_MODULES } from "../../../../../Data/Reasoning/stage2Modules";
import { getActivityById } from "../../../../../Data/Reasoning/activities";
import { readReasoningProgress } from "../../../../../utils/reasoningProgress";
export default function Stage2Verbal(){const router=useRouter();const {user,isAuthenticated}=useSelector((state)=>state.auth);const [progress,setProgress]=useState(null);useEffect(()=>{if(isAuthenticated&&user?.userId)setProgress(readReasoningProgress(user.userId));if(router.isReady&&!isAuthenticated)router.replace("/Auth");},[router.isReady,isAuthenticated,user,router]);if(!router.isReady||!isAuthenticated||!user?.userId)return null;return <><Head><title>Stage 2 · Critical Reading & Argument | Upskilleduonline</title></Head><main style={{minHeight:"80vh",padding:"48px 20px 80px",background:"var(--surface)"}}><div style={{maxWidth:1150,margin:"0 auto"}}><Link href="/Reasoning/Verbal/Dashboard" style={{color:"var(--muted)",textDecoration:"none",fontWeight:700}}>← Back to Verbal Dashboard</Link><p style={{marginTop:28,color:"var(--blue)",fontWeight:800,letterSpacing:".08em",textTransform:"uppercase",fontSize:13}}>Stage 02 · Level 1 · Grade 3</p><h1 style={{fontSize:"clamp(34px,5vw,54px)",lineHeight:1.07,margin:0}}>Critical Reading & Argument</h1><p style={{maxWidth:760,color:"var(--muted)",fontSize:18,lineHeight:1.7}}>Move from basic comprehension to structured critical reading: map arguments, identify assumptions, compare viewpoints and evaluate evidence.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:18,marginTop:30}}>{STAGE2_MODULES.verbal.map((module,index)=>{const activity=(module.activityIds||[]).map(getActivityById).find(Boolean);const finished=activity&&progress?.verbal?.completedActivities?.[activity.id];const moduleDone=progress?.verbal?.completedModules?.[module.id];return <Link key={module.id} href={`/Reasoning/Verbal/Dashboard/Stage2/${module.id}`} style={{textDecoration:"none",color:"inherit"}}><article style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:18,padding:24,height:"100%",boxSizing:"border-box"}}><div style={{color:"var(--blue)",fontWeight:800,fontSize:13}}>MODULE {String(index+1).padStart(2,"0")} · {activity?.half||"practice"}</div><h2 style={{color:"var(--text)",fontSize:21}}>{module.title}</h2><p style={{color:"var(--muted)",lineHeight:1.6}}>{module.focus}</p><div style={{marginTop:16,fontWeight:800,color:finished||moduleDone?"var(--blue)":"var(--muted)"}}>{moduleDone?"Module complete":finished?"Activity complete":"Activity ready"}</div><span style={{display:"inline-block",marginTop:12,padding:"9px 13px",borderRadius:9,background:"var(--blue)",color:"#fff",fontSize:13,fontWeight:800}}>Open module →</span></article></Link>})}</div></div></main></>}
