import Head from "next/head";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useSelector } from "react-redux";
import { useRouter } from "next/router";
import { STAGE3_MODULES } from "../../../../../Data/Reasoning/stage3Modules";
import { getActivityById } from "../../../../../Data/Reasoning/activities";
import { readReasoningProgress } from "../../../../../utils/reasoningProgress";
export default function Stage3Verbal(){const router=useRouter();const {user,isAuthenticated}=useSelector((state)=>state.auth);const [progress,setProgress]=useState(null);useEffect(()=>{if(isAuthenticated&&user?.userId)setProgress(readReasoningProgress(user.userId));if(router.isReady&&!isAuthenticated)router.replace("/Auth");},[router.isReady,isAuthenticated,user,router]);if(!router.isReady||!isAuthenticated||!user?.userId)return null;const modules=STAGE3_MODULES.verbal;return <><Head><title>Stage 3 · Analytical & Scholarly Writing | Upskilleduonline</title></Head><main style={{minHeight:"80vh",padding:"48px 20px 80px",background:"var(--surface)"}}><div style={{maxWidth:1150,margin:"0 auto"}}><Link href="/Reasoning/Verbal/Dashboard" style={{color:"var(--muted)",textDecoration:"none",fontWeight:700}}>← Back to Verbal Dashboard</Link><p style={{marginTop:28,color:"var(--blue)",fontWeight:800,letterSpacing:".08em",textTransform:"uppercase",fontSize:13}}>Stage 03 · Level 1 · Grade 3 · Explore</p><h1 style={{fontSize:"clamp(34px,5vw,54px)",lineHeight:1.07,margin:0}}>Analytical & Scholarly Writing</h1><p style={{maxWidth:780,color:"var(--muted)",fontSize:18,lineHeight:1.7}}>The Explore half develops planning, analytical paragraphs, evidence use, synthesis and revision. The Extend half will be added separately.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:18,marginTop:30}}>{modules.map((module,index)=>{const activity=getActivityById(module.activityIds?.[0]);const done=Boolean(activity&&progress?.verbal?.completedActivities?.[activity.id]);const moduleDone=Boolean(progress?.verbal?.completedModules?.[module.id]);return <Link key={module.id} href={`/Reasoning/Verbal/Dashboard/Stage3/${module.id}`} style={{textDecoration:"none",color:"inherit"}}><article style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:18,padding:24,height:"100%",boxSizing:"border-box"}}><div style={{color:"var(--blue)",fontWeight:800,fontSize:13}}>MODULE {String(index+1).padStart(2,"0")} · EXPLORE</div><h2 style={{color:"var(--text)",fontSize:21}}>{module.title}</h2><p style={{color:"var(--muted)",lineHeight:1.6}}>{module.focus}</p><div style={{marginTop:16,fontWeight:800,color:done||moduleDone?"var(--blue)":"var(--muted)"}}>{moduleDone?"Module complete":done?"Activity complete":"Activity ready"}</div><span style={{display:"inline-block",marginTop:12,padding:"9px 13px",borderRadius:9,background:"var(--blue)",color:"#fff",fontSize:13,fontWeight:800}}>Open module →</span></article></Link>})}</div><div style={{marginTop:28,padding:20,borderRadius:16,background:"var(--card)",border:"1px solid var(--border)",color:"var(--muted)",lineHeight:1.6}}><strong style={{color:"var(--text)"}}>Stage 3 structure:</strong> Explore is available now. Extend is intentionally not included yet and will be built when requested.</div></div></main></>}
